### ISSUE TITLE
fatal error: ooqp/QpGenData.h: No such file or directory

### ISSUE THREAD

**Issue by YouShaoze** [ZJU-FAST-Lab/Visibility-aware-Trajectory-Optimization#2]
/home/ww/visPlanner/src/visPlanner/src/planner/bezier_predict/include/bezier_predict/bezier_predict.h:6:10: fatal error: ooqp/QpGenData.h: No such file or directory
 #include <ooqp/QpGenData.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/ww/visPlanner/src/visPlanner/src/planner/bezier_predict/src/bezier_predict.cpp:1:0:
/home/ww/visPlanner/src/visPlanner/src/planner/bezier_predict/include/bezier_predict/bezier_predict.h:6:10: fatal error: ooqp/QpGenData.h: No such file or directory
 #include <ooqp/QpGenData.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/build.make:62: recipe for target 'visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/src/bezier_predict.cpp.o' failed
make[2]: *** [visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/src/bezier_predict.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/build.make:86: recipe for target 'visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/src/predictor.cpp.o' failed
make[2]: *** [visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/src/predictor.cpp.o] Error 1
CMakeFiles/Makefile2:6355: recipe for target 'visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/all' failed
make[1]: *** [visPlanner/src/planner/bezier_predict/CMakeFiles/bezier_predict.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

请问一下所用的ooqp是哪一个版本啊

**Comment by YouShaoze** [comment]
我的系统环境为ubuntu18.04  ros-melodic CUDA11.4 cudnn8.4.1.50

**Comment by YouShaoze** [comment]
我按照网上说明安装OOQP,环境应该都配置好了,安装了BLAS和MA27,但是编译OOQP的时候出现以下错误:
g++ -O  -Isrc/LinearSolvers/  -Isrc/SparseLinearAlgebra/  -Isrc/Ampl/  -Isrc/Vector/  -Isrc/PetscLinearAlgebra/  -Isrc/QpBound/  -Isrc/Readers/  -Isrc/Svm/  -Isrc/QpSolvers/  -Isrc/Abstract/  -Isrc/QpGen/  -Isrc/Utilities/  -Isrc/Huber/  -Isrc/Mex/  -Isrc/QpExample/  -Isrc/CInterface/  -Isrc/DenseLinearAlgebra/  -Isrc/LinearSolvers/Ma57Solver/  -Isrc/LinearSolvers/Ma27Solver/ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_GETRUSAGE=1   -o qpbound-dense-gondzio.exe \
	src/QpBound/QpBoundDenseGondzioDriver.o src/QpBound/QpBoundDenseLinsys.o src/QpBound/QpBoundDense.o ./lib/libooqpgondzio.a ./lib/libooqpbound.a ./lib/libooqpdense.a ./lib/libooqpbase.a \
	/home/ww/Depend/blas/BLAS-3.10.0/libfblas.a -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lgfortran -lm -lquadmath 
./lib/libooqpdense.a(DeSymPSDSolver.o): In function `DeSymPSDSolver::matrixChanged()':
DeSymPSDSolver.C:(.text+0x4e): undefined reference to `dpotrf_'
./lib/libooqpdense.a(DeSymPSDSolver.o): In function `DeSymPSDSolver::solve(OoqpVector&)':
DeSymPSDSolver.C:(.text+0xe2): undefined reference to `dpotrs_'
collect2: error: ld returned 1 exit status
src/QpBound/MakefileTargets.inc:14: recipe for target 'qpbound-dense-gondzio.exe' failed
make: *** [qpbound-dense-gondzio.exe] Error 1

**Comment by X-DDDDD** [comment]
大佬你好，请问怎样解决的？

**Comment by wangxuexiFINR** [comment]
这个代码时间比较老了，我记得我装的时候也比较麻烦基本上是缺啥装啥然后就能work了
如果OOQP实在装不上的话其实可以不用那部分代码，预测部分其实可以自己写一下的，就是基于之前观测的速度和位置信息拟合一条曲线即可
