### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by X-DDDDD** [ZJU-FAST-Lab/Visibility-aware-Trajectory-Optimization#4]
你好，请问在编译时出现以下信息怎么解决？

Ubuntu20.04，ooqp求解器可以在其他工程中使用，但是在该工程下显示未定义，网上查找无果，特来求教，谢谢:)

`/usr/bin/ld: /home/admin/planning/visPlanner/devel/.private/bezier_predict/lib/libbezier_predict.a(bezier_predict.cpp.o): in function `Bezierpredict::TrackingGeneration(double, double, std::vector<Eigen::Matrix<double, 4, 1, 0, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >)':
bezier_predict.cpp:(.text+0x2e14): **undefined reference** to `QpGenSparseMa27::QpGenSparseMa27(int, int, int, int, int, int)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2ebc): undefined reference to `QpGenSparseSeq::copyDataFromSparseTriple(double*, int*, int, int*, double*, double*, char*, double*, char*, int*, int, int*, double*, double*, int*, int, int*, double*, double*, char*, double*, char*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2f48): undefined reference to `GondzioSolver::GondzioSolver(ProblemFormulation*, Data*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2f9b): undefined reference to `QpGenSparseMa27::QpGenSparseMa27(int, int, int, int, int, int)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x3042): undefined reference to `QpGenSparseSeq::copyDataFromSparseTriple(double*, int*, int, int*, double*, double*, char*, double*, char*, int*, int, int*, double*, double*, int*, int, int*, double*, double*, char*, double*, char*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x30ce): undefined reference to `GondzioSolver::GondzioSolver(ProblemFormulation*, Data*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ego_planner_node_tracker.dir/build.make:192：/home/admin/planning/visPlanner/devel/.private/ego_planner/lib/ego_planner/ego_planner_node_tracker] 错误 1
make[1]: *** [CMakeFiles/Makefile2:226：CMakeFiles/ego_planner_node_tracker.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
/usr/bin/ld: /home/admin/planning/visPlanner/devel/.private/bezier_predict/lib/libbezier_predict.a(bezier_predict.cpp.o): in function `Bezierpredict::TrackingGeneration(double, double, std::vector<Eigen::Matrix<double, 4, 1, 0, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >)':
bezier_predict.cpp:(.text+0x2e14): undefined reference to `QpGenSparseMa27::QpGenSparseMa27(int, int, int, int, int, int)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2ebc): undefined reference to `QpGenSparseSeq::copyDataFromSparseTriple(double*, int*, int, int*, double*, double*, char*, double*, char*, int*, int, int*, double*, double*, int*, int, int*, double*, double*, char*, double*, char*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2f48): undefined reference to `GondzioSolver::GondzioSolver(ProblemFormulation*, Data*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x2f9b): undefined reference to `QpGenSparseMa27::QpGenSparseMa27(int, int, int, int, int, int)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x3042): undefined reference to `QpGenSparseSeq::copyDataFromSparseTriple(double*, int*, int, int*, double*, double*, char*, double*, char*, int*, int, int*, double*, double*, int*, int, int*, double*, double*, char*, double*, char*)'
/usr/bin/ld: bezier_predict.cpp:(.text+0x30ce): undefined reference to `GondzioSolver::GondzioSolver(ProblemFormulation*, Data*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ego_planner_node_target.dir/build.make:192：/home/admin/planning/visPlanner/devel/.private/ego_planner/lib/ego_planner/ego_planner_node_target] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1765：CMakeFiles/ego_planner_node_target.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
cd /home/admin/planning/visPlanner/build/ego_planner; catkin build --get-env ego_planner | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

............................................................................................................................................................
Failed     << ego_planner:make                       [ Exited with code 2 ]                                                                                 
Failed    <<< ego_planner                            [ 0.6 seconds ]                                                                                        
[build] Summary: 21 of 22 packages succeeded.                                                                                                               
[build]   Ignored:   None.                                                                                                                                  
[build]   Warnings:  None.                                                                                                                                  
[build]   Abandoned: None.                                                                                                                                  
[build]   Failed:    1 packages failed.                                                                                                                     
[build] Runtime: 1.6 seconds total. `

**Comment by wangxuexiFINR** [comment]
不好意思我没有在20系统里用过欸，但是我看好几个issue都说到了ooqp的问题，我感觉可能是我们的代码在用这个库的时候也不太规范导致的，我建议是要不就把这部分与其相关的都换掉，自己写一下，这个功能，或者之后我我想想能不能替换一下这个包的函数

**Comment by wangxuexiFINR** [comment]
其实这个部分就是求解一个比较干净的qp问题，我觉得如果你对qp比较熟悉的话，直接换个求解器也行的
