### ISSUE TITLE
In your paper it was mentioned Hybrid A*, but D* is used

### ISSUE THREAD

**Issue by brunopinto900** [ZJU-FAST-Lab/Visibility-aware-Trajectory-Optimization#5]
Can you explain why? Because i am choosing between these search algorithms for my thesis and i would like to know why do you chose D* instead.

**Comment by wangxuexiFINR** [comment]
Our algorithm has a completely different process than the D* algorithm. In this work, we take the hybrid A* in fastplanner and improve it to fit our task.
